### ISSUE TITLE
Secure Plugins

### ISSUE THREAD

**Issue by blacktop** [maliceio/malice#49]
# TODO

 - [ ] create a seccomp profile for different plugin types
 - [ ] create default cgroup settings
 - [ ] drop most capabilities

https://docs.docker.com/engine/security/seccomp/
https://docs.docker.com/engine/admin/resource_constraints/

### seccomp
HostConfig. SecurityOpt

### cgroup settings
HostConfig.Resources.Memory

### drop most capabilities
HostConfig.CapAdd
HostConfig.CapDrop

**Comment by blacktop** [comment]
See https://github.com/maliceio/registry
